### ISSUE TITLE
Does not work with IE6

### ISSUE THREAD

**Issue by 24js** [weblinc/jquery-parallax#5]
It seems it doesn't work in IE6 , i did tested both online demos in IETester , works fine with IE7+ but no luck get it work with IE6

**Comment by meowsus** [comment]
I'm not even sure an operating system works with IE6 anymore.

**Comment by 24js** [comment]
@meowsus 
:) 2 year ago i asked this ( it's like 10 years in github ) , when there was few IE6 users on our website analytics, back then when i searched i found that jquery-parallax has a polyfill for IE6

**Comment by meowsus** [comment]
I figured there was a good reason. Super sorry for the delay in the response.
