### ISSUE TITLE
Demo not working 

### ISSUE THREAD

**Issue by Ataurr** [weblinc/jquery-parallax#6]
I have just tried with chrome and firefox found its not working in demo.

can you please check.

Thanks

**Comment by meowsus** [comment]
Hey @Ataurr 

I just checked `demo/index.html` in the repo in Chrome 52.0.2743.116 (64-bit) and Firefox 37.0.1 and it's working for me, albiet a bit laggy. The [public demos](http://weblinc.github.io/jquery-parallax/) seem to be working fine as well.

Not too bad for a 4 year old jQuery Plugin :D

Let me know if you have some steps to help me reproduce the issue you're seeing. I'll close this issue now and reopen if necessary.
